import arcpy, time
import os
import sys
from arcpy.sa import *

GNAF_FC = arcpy.GetParameterAsText(0)         # Required & Typed GNAF Point FeatureClass needs to exist and fields as per script

arcpy.management.AddIndex(GNAF_FC, "SA1_7DIGITCODE_2016", "SA1_7DIGITCODE_2016", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("SA1_7DIGITCODE_2016: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "LGA_NAME18", "LGA_NAME18", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("LGA_NAME18: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "LGA_NAME16", "LGA_NAME16", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("LGA_NAME16: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "POA_CODE16", "POA_CODE16", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("POA_CODE16: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "SSC_NAME16", "SSC_NAME16", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("SSC_NAME16: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "SA4_CODE16", "SA4_CODE16", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("SA4_CODE16: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "SA3_CODE16", "SA3_CODE16", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("SA3_CODE16: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "SA2_MAIN16", "SA2_MAIN16", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("SA2_MAIN16: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "SA1_MAIN16", "SA1_MAIN16", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("SA1_MAIN16: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "MB_CAT16", "MB_CAT16", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("MB_CAT16: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "MB_CODE16", "MB_CODE16", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("MB_CODE16: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "MB_CODE_2016_N", "MB_CODE_2016_N", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("MB_CODE_2016_N: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "PROPERTY_PID", "PROPERTY_PID", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("PROPERTY_PID: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "GNAF_PROPERTY_PID", "GNAF_PROPERTY_PID", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("GNAF_PROPERTY_PID: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "ADDRESS_DETAIL_PID", "ADDRESS_DETAIL_PID", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("ADDRESS_DETAIL_PID: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "ADDRESS_SITE_PID", "ADDRESS_SITE_PID", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("ADDRESS_SITE_PID: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "LOCALITY_PID", "LOCALITY_PID", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("LOCALITY_PID: Indexed. - {}".format(time.strftime("%X")))
arcpy.management.AddIndex(GNAF_FC, "LOCALITY_NAME", "LOCALITY_NAME", "NON_UNIQUE", "NON_ASCENDING")
arcpy.AddMessage("LOCALITY_NAME: Indexed. - {}".format(time.strftime("%X")))
arcpy.AddMessage("{} Indexing Finished. - {}".format(GNAF_FC, time.strftime("%X")))