# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-11-27 11:11:14
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    Incidents_xy = r'S:\CoreData\NCIS\LITS_20200729\NCIS.gdb\Incidents_xy'

    # Process: Kernel Density (Kernel Density) (sa)
    MB_Rescale_1k_KD_Suicide_Inc_08_17_Total_P = "F:\\Suicide_Vs_Population\\LITS_20200729\\Suicide_2008-2017_KDs.gdb\\MB_Rescale_1k_KD_Suicide_Inc_08_17_Total_P"
    Kernel_Density = MB_Rescale_1k_KD_Suicide_Inc_08_17_Total_P
    MB_Rescale_1k_KD_Suicide_Inc_08_17_Total_P = arcpy.sa.KernelDensity(in_features=Incidents_xy, population_field="NONE", cell_size="200", search_radius=1000, area_unit_scale_factor="SQUARE_KILOMETERS", out_cell_values="DENSITIES", method="PLANAR", in_barriers="")
    MB_Rescale_1k_KD_Suicide_Inc_08_17_Total_P.save(Kernel_Density)


    # Process: Con (Con) (ia)
    MB_Con_1k_KD_Suicide_Inc_08_17_Total_P = "F:\\Suicide_Vs_Population\\LITS_20200729\\Suicide_2008-2017_KDs.gdb\\MB_Con_1k_KD_Suicide_Inc_08_17_Total_P"
    Con = MB_Con_1k_KD_Suicide_Inc_08_17_Total_P
    MB_Con_1k_KD_Suicide_Inc_08_17_Total_P = arcpy.ia.Con(in_conditional_raster=MB_Rescale_1k_KD_Suicide_Inc_08_17_Total_P, in_true_raster_or_constant=MB_Rescale_1k_KD_Suicide_Inc_08_17_Total_P, in_false_raster_or_constant="", where_clause="VALUE > 0")
    MB_Con_1k_KD_Suicide_Inc_08_17_Total_P.save(Con)


    # Process: Rescale by Function (Rescale by Function) (sa)
    MBx_Rescale_1k_KD_Suicide_Inc_08_17_Total_P = "F:\\Suicide_Vs_Population\\LITS_20200729\\Suicide_2008-2017_KDs.gdb\\MBx_Rescale_1k_KD_Suicide_Inc_08_17_Total_P"
    Rescale_by_Function = MBx_Rescale_1k_KD_Suicide_Inc_08_17_Total_P
    with arcpy.EnvManager(compression="NONE", pyramid="NONE"):
        MBx_Rescale_1k_KD_Suicide_Inc_08_17_Total_P = arcpy.sa.RescaleByFunction(in_raster=MB_Con_1k_KD_Suicide_Inc_08_17_Total_P, transformation_function=[["LINEAR", 0, "", 60.44379806518555, "", 0, 60.44379806518555, ""]], from_scale=0, to_scale=20)
        MBx_Rescale_1k_KD_Suicide_Inc_08_17_Total_P.save(Rescale_by_Function)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"F:\Suicide_Vs_Population\LITS_20200729\Suicide_2008-2017_KDs.gdb", workspace=r"F:\Suicide_Vs_Population\LITS_20200729\Suicide_2008-2017_KDs.gdb"):
        Model()
